"""Unison brain Python SDK."""
from __future__ import annotations

from . import types
from ._client import AsyncClient, AsyncUnisonBrain, Client, UnisonBrain
from ._exceptions import (
    APIConnectionError,
    APIError,
    APIStatusError,
    APITimeoutError,
    AuthenticationError,
    BadRequestError,
    BrainContractError,
    ConflictError,
    InternalServerError,
    NotFoundError,
    PermissionDeniedError,
    RateLimitError,
    UnisonError,
    UnprocessableEntityError,
)
from ._version import __title__, __version__
from .types import (
    BrainDocument,
    BrainEntity,
    BrainFact,
    BrainLink,
    BrainStatus,
    DeviceCodeResponse,
    EntityListResponse,
    EntityResolveResponse,
    FactListResponse,
    FsEntry,
    FsListResponse,
    FsReadResponse,
    GrepResponse,
    InvalidateFactResponse,
    JobItem,
    JobListResponse,
    JobStatsResponse,
    LinkListResponse,
    ListResponse,
    ProvisionResponse,
    RequestKeyResponse,
    SearchResponse,
    SearchResult,
    ShareResponse,
    TokenResponse,
    VerifyResponse,
    WhoAmIResponse,
)

__all__ = [
    "types",
    "__version__",
    "__title__",
    # Clients
    "UnisonBrain",
    "AsyncUnisonBrain",
    "Client",
    "AsyncClient",
    # Errors
    "UnisonError",
    "APIError",
    "APIStatusError",
    "APITimeoutError",
    "APIConnectionError",
    "BadRequestError",
    "AuthenticationError",
    "PermissionDeniedError",
    "NotFoundError",
    "ConflictError",
    "UnprocessableEntityError",
    "RateLimitError",
    "InternalServerError",
    "BrainContractError",
    # Response types
    "WhoAmIResponse",
    "ProvisionResponse",
    "VerifyResponse",
    "RequestKeyResponse",
    "DeviceCodeResponse",
    "TokenResponse",
    "BrainDocument",
    "BrainEntity",
    "BrainFact",
    "BrainLink",
    "BrainStatus",
    "SearchResponse",
    "SearchResult",
    "GrepResponse",
    "ListResponse",
    "FsEntry",
    "FsListResponse",
    "FsReadResponse",
    "EntityListResponse",
    "EntityResolveResponse",
    "FactListResponse",
    "InvalidateFactResponse",
    "LinkListResponse",
    "ShareResponse",
    "JobItem",
    "JobListResponse",
    "JobStatsResponse",
]
